# Generated by Django 5.2 on 2025-04-29 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessoEsterilizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('concluido', 'Concluído'), ('falha', 'Falha')], default='pendente', max_length=20)),
                ('usuario_responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EtapaProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_etapa', models.CharField(choices=[('recebimento', 'Recebimento'), ('lavagem', 'Lavagem'), ('esterilizacao', 'Esterilização'), ('distribuicao', 'Distribuição')], max_length=20)),
                ('data_realizada', models.DateTimeField(auto_now_add=True)),
                ('falha', models.BooleanField(default=False)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.material')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='users.processoesterilizacao')),
            ],
        ),
    ]
