# Generated by Django 5.2 on 2025-04-30 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_processoesterilizacao_etapaprocesso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processoesterilizacao',
            name='usuario_responsavel',
        ),
        migrations.DeleteModel(
            name='EtapaProcesso',
        ),
        migrations.DeleteModel(
            name='ProcessoEsterilizacao',
        ),
    ]
