# Generated by Django 5.2 on 2025-04-30 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_processoesterilizacao_usuario_responsavel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtapaProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(choices=[('recebimento', 'Recebimento'), ('lavagem', 'Lavagem'), ('esterilizacao', 'Esterilização'), ('distribuicao', 'Distribuição')], max_length=20)),
                ('data_realizacao', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='users.material')),
            ],
            options={
                'ordering': ['data_realizacao'],
            },
        ),
    ]
