# Generated by Django 5.2 on 2025-04-30 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_etapaprocesso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etapaprocesso',
            name='material',
        ),
        migrations.CreateModel(
            name='Procedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedimentos', to='users.material')),
            ],
        ),
        migrations.AddField(
            model_name='etapaprocesso',
            name='procedimento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='users.procedimento'),
            preserve_default=False,
        ),
    ]
