# Generated by Django 5.2 on 2025-04-30 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_etapaprocesso_material_procedimento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapaprocesso',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='pendente', max_length=20),
        ),
    ]
