# Generated by Django 5.2 on 2025-04-30 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_etapaprocesso_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapaprocesso',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('em andamento', 'Em andamento'), ('concluida', 'Concluída')], default='pendente', max_length=20),
        ),
    ]
