# Generated by Django 5.2 on 2025-04-30 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_etapaprocesso_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Falha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('data_ocorrencia', models.DateTimeField(auto_now_add=True)),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='falhas', to='users.etapaprocesso')),
            ],
        ),
    ]
